version: '3'

services:
  web:
    build: .
    command: gunicorn techflex_cms.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: techflex
      POSTGRES_USER: techflex
      POSTGRES_PASSWORD: techflexpass
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  static_volume:
  media_volume:
